version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - rm package-lock.json
  pre_build:
    commands:
      - echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
      - echo "@OWNER:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - echo Installing NPM packages...
      - npm install
  build:
    commands:
      - echo Starting build...
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/main" ]; then
          echo "Running production build"
          ng build --configuration production
        else
          echo "Running development build"
          ng build
        fi
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/carriersDashboard