version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - yarn add @angular-devkit/build-angular@12.2.16 --dev
  build:
    commands:
      - echo Starting build...
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/carriersDashboard