version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - rm package-lock.json
    pre_build:
      commands:
      - echo Installing NPM packages...
      - npm install
  build:
    commands:
      - echo Starting production build...
      - ng build --configuration production
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/carriersDashboard